### ISSUE TITLE
Compile fails with sdfat library version higher than 1.1.4

### ISSUE THREAD

**Issue by flegmatik** [mad3001/Multiply#1]
You need sdfat library version 1.1.4, it would be a good idea to include this in documentation.

**Comment by mad3001** [comment]
Try now

**Comment by flegmatik** [comment]
Arduino 1.8.19, sdfat library version 2.2.0

Now it fails with:

Multiply_Arduino:1:10: fatal error: BlockDriver.h: No such file or directory
 #include <BlockDriver.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
exit status 1
BlockDriver.h: No such file or directory

**Comment by mad3001** [comment]
Well I had an old version of sdfat "in the shadow" of arduino into the libraries from version 1.1.4 that helped to compile.
New versions of sdfat changed, at least, these calls:
- chdir (char * path, bool)  => chdir (char * path).
-getSFN (char * path) =>  getSFN(char* name, size_t size)
But that is not enough... at this moment changing these, although it compile, it broke something in the load TAP files subroutines, maybe something else was changed into the sdfat library.
At this moment is recommended to continue using sdfat 1.1.4.

**Comment by flegmatik** [comment]
Yeah, nothing wrong with that, it works great.

**Comment by mad3001** [comment]
Thank you for your report. I have added which versions of sdfat can be used ... now you have two options for sdfat, and both are working in IDE 1.8.x or IDE 2.0.x
I'll try to check what breaks the TAP load with sdfat version 2.0
