### ISSUE TITLE
Bomb icon during the USB transfer

### ISSUE THREAD

**Issue by spawnerbr** [mad3001/Multiply#4]
Hi all. I got some days ago a Multiply module for my ZX Dandanator Mini. As I used before it to transfer some files to my Amstrad Dandanator Mini, I have the drivers installed on Win10, so the module was detected. First thing that I did was turn the ZX on while pressing the two Dandanator buttons. The seller told me that this is necessary to update the Dandanator to use the Multiply.

Then I try to transfer the ROM created only with LOADER MULTIPLY. Fail. I transferred using USB and after finish the 1st block, at the beginning of block 2 I got a bomb icon. So, using the java app, I tried Update Multiply. First time red icon on UPDATED, then tried again and green icon.

Tried again and same bomb icon. No green squares to show that is complete before the 2nd block.
Any idea to help me? Thanks!

![WhatsApp Image 2024-09-23 at 15 02 48](https://github.com/user-attachments/assets/05a2bede-34a4-403b-a974-95af29fa9e9d)

**Comment by mad3001** [comment]
Hi spawnerb, the first thing you need to do is to make the small modification to your dandanator. Check the documentation and follow the instructions for removing C3 (not C4) and connect the 1-wire necessary for it to work properly.

**Comment by spawnerbr** [comment]
Thanks for your reply @mad3001 . I tried this before the steps for the Multiply. First thing that I tried was to send the "ROM" file to the Dandanator using the USB cable. So, I got the bomb icon. Then I removed the Arduino Nano and used other one that I have that looks official. I write the hex file to the Arduino and then sent "ROMs" to the Dandantor using the java app. worked perfectly. Next step was to connect the Arduino Nano on the PC and do the Multiply Updater. Update done, green icon. Inserted Arduino on the Multiply. Tried to access the Multiply and "Multiply NOT DETECTED" message.  So I removed the cap and did the wire. I accessed the Multiply file manager but tried 3 microSD cards and it is not listing the contents. Tried two 2GB that I use here and an original SanDisk 32GB. Still not listing. I'm stuck on that part now and dunno what to do. I replace with other microSD reader and nothing changed. As it uses a socket bar for the card reader, tomorrow will try to solder directly to the board. But there something I'm doing wrong?

I have other question: After do the mod (cap and wire) the Dandanator cannot receive more files using the USB port from the Java app? The only way now will be creating the ROM sets, copying to the Micro SD and program the eprom from the Multiply file manager?

**Comment by mad3001** [comment]
Hello again... I recommend you to follow these steps:
1.-Go to the overCLK github where you can find the latest version of the Dandanator mini ROMSET 10.4.3 generator https://github.com/teiram/dandanator-mini/packages/1056234
2.-Connect a USB cable between the PC and the Multiply... Do not connect the Multiply to the Dandanator, leave it alone.
3.-Launch the ROMSET generator version 10.4.3. 
4.-Through the menu go to the option ‘Update Multiply’.
5.-Select the COM port for the Arduino... I recommend disabling bluetooth to avoid Bluetooth COM ports appearing. You can use refresh to update the COM ports if you connected the Multiply after starting the romset generator.
6.-Click ‘Update’.

Once the Arduino is in its latest version try again.

Tips:
a) Use the official SD card formatter of the SD Association: https://www.sdcard.org/downloads/formatter/
It is easy to use and will format your microsd in the correct format. SD can be FAT 16 or FAT 32, but neither EXFAT nor NTFS.
b) In the Dandanator, follow the wiring you did to Pin 9 to be sure you connected in the correct pin of C3 footprint... What Dandanator version you have? V2.0, V2.1, V2.1b ... 
Regarding the question about the behaviour of the dandantor. Removing C3 and wiring to pin 9 does not change the behaviour of the dandanator. Don't worry about that, you can still use Dandanator without Multiply as always.

**Comment by spawnerbr** [comment]
I did yesterday all the steps like you wrote. The only thing that I did not the same ways yesterday was run Update Multiply with the Arduino Nano connected to the Multiply. I did it out from the Multiply. So, today I repeat all the steps like you wrote and same thing "Multiply NOT DETECTED".

I always use SD Card Fomatter on Windows and Mac. Yesterday I formatted again the cards and nothing changed.

My Dandanator is 2.1 version. I think I will try to solder the card reader directly to the Multiply PCB as the seller sold with a socket to remove it easily.

About "remove C3 and wiring". Yes, the Dandanator works but only because I have 3 files on the ROM that I sent before the mods. After this I cannot send more files using the USB/Arduino. This is normal? Cause the only way now will be send files through the Multiple File Manager?

![tela1](https://github.com/user-attachments/assets/f7e677ac-0288-4c4f-858b-7c9a26115b8a)

![tela2](https://github.com/user-attachments/assets/eaf23738-772e-4590-9593-ae190d4f4874)

![tela3](https://github.com/user-attachments/assets/7d315651-a91a-42b9-80eb-eaa67844f419)

![IMG_1936](https://github.com/user-attachments/assets/6887d935-3e73-4068-8130-ddd1fbfd8424)

![IMG_1935](https://github.com/user-attachments/assets/270b540d-469b-453b-88ba-9545612909a3)

**Comment by liveboxandy** [comment]
Can you check the solder at the highlighted pin?
![DandanatorFlash](https://github.com/user-attachments/assets/86894afe-1a12-4108-b609-70d282e440f7)

**Comment by spawnerbr** [comment]
@liveboxandy yes, rechecked, solder again and nothing changed.

**Comment by spawnerbr** [comment]
Maybe I'm missing this?
"Both Buttons - Updates the PIC microcontroller firmware with the software stored in the installed romset."
I have tried before, but in which step I need it and the purpose?

**Comment by liveboxandy** [comment]
Might not be related but what EEPROM is installed?
Can you provide a photo of the top of the Dandanator?
Also, I am sure that the PIC code late 2020 is needed for Multiply support.
Do you access to an EEPROM programmer?

**Comment by spawnerbr** [comment]
@liveboxandy Using the Dandanator with Multiply and not removing the capacitor and doing the wire to the DB9, I can programmer using dandanator-mini-10.4.3 without problem. About the PIC that is a good point cause I bought this Dandanator Mini 2.1 from a friend on 2020, so there is a possibilty about the PIC.

But there are a lot of steps that I'm now confused what to do. So what I did:

Downloaded "Multiply_Arduino.ino.eightanaloginputs.hex" from https://github.com/merlinkv/ZX_Dandanator_MTD/tree/main/Firmware

I can't find other source with the Arduino NANO files to program using AVRDUDE, so used that.
After write the HEX I opened dandanator-mini-10.4.3.jar and did MULTIPLY UPDATER and it passes with green icon.
Before do the mod of the cap and wire, I transferred some games to the Dandantor, including the LAUNCH MULTIPLY.
I did the mod of the cap and wire to the DB9.

Here is the point that I have a doubt. A friend told me that the PIC can be updated automatically pressing both Dandanator buttons and turning the ZX on. And it shows that it will upgrade. So have two doubts:

1) The file to update is not that "Multiply_Arduino.ino.with_bootloader.eightanaloginputs.hex" that has a bootloader to do that update to the PIC? If yes, I got error when I try to write do Arduino. Only "Multiply_Arduino.ino.eightanaloginputs.hex" is working.

2) This PIC update pressing two buttons must be done before the mod (cap/wire) or after?

Thanks

**Comment by mad3001** [comment]
@spawnerbr go step-by-step
What files did you copy to the SD card? please make two or three empty folders to see if they appear in the multiply menu... also make sure the files are TAP, SNA, Z80, SCR... any other file extension will be ignored so they will not appear in the multiply menu.
Regarding the firmware... pressing both buttons at startup will update the PIC firmware.
I recommend you not to use HEX files and external programs like avrdude or others... even these can load the firmware your HEX file may be the wrong one to be used in conjunction with the PIC firmware...
I recommend you use the link to mteira github ( https://github.com/teiram/dandanator-mini/packages/1056234 ) which is the latest version of the ROM generator and will upload the correct file to your Arduino.

One test you can do is, using a joystick plugged in multiply, press fire in your Multiply "empty" menu to go to Dandanator menu... then try to go UP-DOWN in the menu... if these works fine turn off the spectrum, press right button of dandanator and without releasing turn on the spectrum... wait up to appearing the Sinclair welcome screen... 
Type this little program at basic:
10 PRINT AT 0,0;IN31;"  ": GOTO 10
and run it... move joystick (plugged in Multiply) and check it shows in screen the values for each direction: 16 for Fire, 8 for Up, 4 for Down, 2 for Left, 1 for Right...

One more thing... the arduino's hex files have nothing to do with updating the PIC firmware... The PIC firmware is updated with the content stored in the EEPROM when you press the two buttons (so Multiply is not necessary for that, you can disconnect it before doing the operation). The only thing that is required here is that the EEPROM has been prepared with the ROMSET generator and flashed (the first time it is flashed with an EEPROM programmer like the TL866) but you say you have it with a romset...Can you take a picture of the screen obtained if you start with the multiply not plugged in (dandanator only)?
Notice: C3 is removed to avoid communication problems as the cable connected to Pin9 is necessary for Serial transmission between the Dandanator and the Multiply. If you leave C3 on the board you may have more problems because it is stretching the signals for the Serial transmission from the PIC to the Arduino required for the commands between them.

**Comment by spawnerbr** [comment]
@mad3001 

I created folders and used files from my DivMMC like TAP e SNA. Before continue, this is the picture with the ROM SET created from me using the 10.4.3 ROM Generator. I did the Updater Multiply too. Dunno if this is correct, but after the mod (cap and wire) I cannot send the ROM SET using the Arduino from USB. The only way to do that is put the cap again and removing the wire. This is correct? Cause I watch some videos that now the way to write ROM SET is using the file manager on Multiply and selecting the ROM file.

![IMG_1949](https://github.com/user-attachments/assets/48f21358-6081-4d1b-836e-23250c8e0e08)

**Comment by mad3001** [comment]
The Dandanator ROM version is correct, it shows v10.4.3. 
Did you do the BASIC program to test Multiply is sending correctly the Joystick movements to the speccy? If no please do it as first thing.
If kempston works fine going from Joystick to Multiply and from there to Dandanator then you can proceed with the following procedure:
In your PC run ROMSET generator v10.4.3.
In the menu select ‘Extra -> Add Multiply launcher.....’.
You can also add some TAP, Z80 or whatever.
Now connect the USB cable from your PC to the Multiply, connect the Multiply to the Dandanator and the Dandanator to your speccy. Do not turn on the speccy at this point.
Back to your PC, in Romset Generator go to the ‘File->Preferences’ menu and in the next window go to the ‘Loader’ tab.
Click on the refresh icon (the 2 arrows icon) and select the COM port of your Arduino which should appear there in the combobox under ‘Serial Port->Kempston’.
Click on the ‘Serial Port->Kempston’ check.
AND make sure to UNcheck the ‘Send Writer via audio’ option.
Close the ‘Preferences’ window.
On the main ROM Generator screen in the top left box where the ZX Dandanator menu appears with the games you will notice 2 little balls, one white and one black, click on this little black ball and you will see the ‘romset loader’. If "cassette" loader appear then something is wrong with Multiply pcb and/or ribbon cable.
If you see the 'romset loader' then you have to go back to your speccy and turn it on, you have to be in the Dandanator menu to press L to go to the ‘EEPROM WRITER’.
Now go to your PC and in ‘romset loader’ press the PLAY button.
It should start sending the romset to dandanator, you should see the progress of the 16 blocks to be written.

**Comment by spawnerbr** [comment]
@mad3001

The kempston is working on games, working to load games from Dandanator menu, and inside the Multiply File Manager is going back to the first Dandanator screen. The BASIC worked with all values that you said.

Now, that is a problem. After the mod (cap and wired) when I start to send the ROM from ROMSET generator it flash the border on blue fast and nothing is sent. Then it goes back to the startup screen. The only way to write the EEPROM using this method is removing the wire and putting the cap again on the board. No way to flash the EEPROM with the mod. So, to create this menu that you see the pic, I put the cap again and transferred the ROM SET using USB cable, then did the mod again. And the joystick is showing on the ROMSET LOADER.

So that are the problem:

1) I only sent files to the EEPROM using USB cable through the Arduino, but it only works before the mod on the Dandanator. With mod, the EPPROM WRITER on ZX wait the play on ROMSET LOADER but only the border flash fast the on blue. Before the mod It load all 16 blocks, writing using green dots and the border is on blue like loading a tape game.

2) Access of the files on microSD. I tried 5 microSD cards that I use on my interfaces. No one changed anyhting. I used SD Formatter as usual to format my cards. Then I tried with other card reader from a IC tester that I have. No file is showing.

That are the two problems that I have. Think I will quit :(

**Comment by mad3001** [comment]
OK, we can try again tomorrow...
In the meantime I leave here 2 questions for clarification:
When you say ‘The kempston works in games, it works to load games from the Dandanator menu’, it means the Joystick connected in Multiply and Multiply with the ribbon-cable to the Dandanator.... is it like that?
One weird thing is with the problem you say of leaving the Cap and no cable you can use EEPROM writer via USB cable to Multiply and it updates correctly but with the Cap removed and the cable soldered you can't load that way? Is this the case?

**Comment by spawnerbr** [comment]
@mad3001 

I never tried the joystick directly on the Dandanator. I bought on 2020 this Dandanator from a friend and only on the latest weekend I bought the Multiply from other friend. And he mounted a lot. All this tests are with the Kepston on the Multiply using the ribbon-cable (flat cable).

The multiply came with an Arduino NANO that everytime that I tried to wrote the EEPROM, I got a bomb icon on ZX. That was the beginning of all. So this NANO looks fake, bad. I replaced with a new one from my electronics and this one worked to send the ROM to the ZX, but after the mod, I can't send more files from the PC to the ZX. Only If I back with the cap and remove the wire.

Really dunno why.

**Comment by mad3001** [comment]
If you can check with a friend who has another "working" Multiply? I think there is something wrong with that Multiply because all the tests you have done point to it.

**Comment by spawnerbr** [comment]
@mad3001 he only have now the Dandanator MTD. I tried to find today some store with Dandanator + Multiply but all are out of stock. Will find a way to test this. Thanks for all

**Comment by mad3001** [comment]
Try this approach, remove cap C3 but this time solder the wire from db9 to this point (red circle). 
![IMG_20240925_053757_761](https://github.com/user-attachments/assets/f98c6ae4-53f5-4593-8c08-0ca4c831308b)

**Comment by spawnerbr** [comment]
Hi @mad3001 Tried and nothing changed. The only thing that happens is that sometimes when I turn the ZX on it goes directly to the Multiply File Manager without pressing anything on keyboard or joystick. Tried again with a microSD from my TZXduino and no files on the screen. And not writing EEPROM too.

**Comment by mad3001** [comment]
Then I recommend you to check Multiply on another Dandanator or vice versa. I guess you are not in Spain that could help you to find a ‘cheap’ way to send me your Multiply to do a full check of it.

**Comment by spawnerbr** [comment]
@mad3001 I'm from Brazil :) Will try to find a complete Dandanator with Multiply using Arduino Nano to test or to buy and I come back with news. Thanks for the help!

**Comment by spawnerbr** [comment]
@mad3001 I'm back. Today I removed the micro SD card module that came with the Multiply and replaced with a new one that I bought and finally accessed the files on the micro SD card :) Happy with this. Dunno what was the problem, but it is working now.

But I still have some problems:

Before do the mod using the original Arduino NANO that came with Mulitply, it shows a bomb icon before write the 1st slot using the java app. After the mod to using the Multiply I have the same problem.

Replaced the Arduino NANO with other new that I have. Before the mod I can send files files to the EPROM using the java app. After the mod, it tries to send the 1st slot, border flashes on blue and goes to the first screen (the one with the snaps to select).

Just for a test, I tried to run dandanator-mini-10.4.1.jar., I did the update on the Arduino and the turned the ZX on with the two buttons pressed. He show the PIC message, but nothing changed. Still with the 10.4.3

Doubts:

1) I tried to downgrade the version of the Dandanator just to do a test here, but what I did to downgrade is correct?

2) Any other idea about this problem that I have after the mod to send files to the EPROM? Maybe a problem with the ports of the windows?

3) My Dandantor Mini is before the creation of the Multiply. I checked from my friend that sold to me. Maybe electronic component have changed after the Multiply?

4) Just to confirm, the PIC is written with the Arduino NANO updates from the java app and turning the computer on pressing the two buttons and holding them?

Thanks!

![IMG_2010](https://github.com/user-attachments/assets/d32420cb-04f9-4115-ab12-f5fcdd0b52b6)

**Comment by mad3001** [comment]
Hi @spawnerbr
The version 10.4.3 shown is related to the content of the EEPROM. You should generate a new ROMSET with the 10.4.1.jar and write it to the EEPROM so that it correctly shows the 10.4 or 10.4.1 version. Also with this new ROMSET you should hold down both buttons at startup for the PIC update so that both are synchronised. 
Dandantor v2.1 is fine to run with multiply and the removal of C3 by putting the DB9 pin 9 wire from the kempston to the point on the old C3 that IS NOT connected to ground.
If you have followed the instructions as per the DOCS pdf manual then it should be ok.
Anyway 10.4.3 should work with your setup. Can you take a picture of both sides of the Multiply? only to be sure pcb it is the correct version of it (which if it is the same as the one posted on github should be the correct one, but we better confirm).
Regards

**Comment by spawnerbr** [comment]
Hi @mad3001
After thinking about it, I tried to run Windows 7 here to try other way.


Connected the Multiply with the Arduino NANO (with Micro USB) that came with it. This one that I got a bomb icon previously. Win7 recognized the Arduino as CH340. Tried again to send and bomb icon. So, on the Device Manager I removed the device with delete drivers checked. Then emoved and inserted the Arduino on USB. Recognized on Device Manager. Removed the device with delete drivers checked again. Remove and inserted the Arduino on USB. Recognized.

Now, time to try again to send the ROM set. Starting the transfer, the board flashes on blue fast but stopped the transfer. So I entered on Device Manger to check the COM settings. I changed the speed of the COM from 9600 to 115200. Started to send again the ROM to the Dandanator: border started to working during the transfer and no bomb icon after the first slot. All 16 slots was transferred and EPROM updated to a new one :)

Now, still on Win7 I tried with my Arduino NANO that has micro USB. Border flashes on blue but stop the transfer. Will not insist with this Arduino cause the other one worked.

So, replaced the SSD with Win10, did the same steps: Arduino on USB, removed device from Device Manager deleting the drivers... Start the transfer and no bomb icon and all slots transferred :)

My first attempt with Dandanator Mini was with the Amstrad version and I did the installation of the CH340 drivers as a guide that I read:

https://www.amstrad-noob.com/2021/02/21/programming-a-mini-dandanator/

Maybe it screw my Windows 10 with bad drivers, dunno. But it is working now. I tried to before to select COM ports with low numbers, but impossible. So always using COM 7-11 here.

Other question is about the Arduino NANO with mini USB that is not working. Hate this cause dunno the reason. Fake maybe?

Thanks for all the help and now I have a 100% Dandanator with Multiply!
Here the pics of my Arduinos.

![arduino nano](https://github.com/user-attachments/assets/41281058-3092-4153-8f06-ba62806b4527)

**Comment by liveboxandy** [comment]
Hi @spawnerbr,

What types of Arduino Nano do you have ?
I have some with the ATMEGA328P chip but also some with a ATMEGA168P chip.
Both are classed as Arduino Nano.
The 168 has only 16K Flash, 512Byte EEPROM and 1K RAM compared to
the 328 that has 32k Flash, 1K EEPROM and 2K RAM.

Andy

**Comment by spawnerbr** [comment]
@liveboxandy both are 328P but I think the problem here is not about size or memory, is about communication. Now the original that came with Multiply is working as I described above. And one that I have here is not working on the USB. Only works If I remove the multiply mod on the Dandantor.

**Comment by liveboxandy** [comment]
Fair enough, just thought I'd ask.

AndyP

**Comment by spawnerbr** [comment]
@liveboxandy using AVRDUDESS 2.18 Portable the one that has a communication problem is 1e950f = ATmega328P, with 32KB Flash and 1KB EEPROM. Arduino Nano ATmega328P.

**Comment by mad3001** [comment]
Good to hear that you were finally able to write the EEPROM correctly ... indeed sometimes the serial port drivers are not the correct ones depending on what serial chip the particular arduino nano uses... as far as I know there are at least 7 variants of CH340 and some of them use different drivers.
Regarding the atmega versions, usually the boards with atmega168p are green or red, not blue which is the usual for those with atmega328p.
Thanks @spawnerbr and @liveboxandy ....

**Comment by mad3001** [comment]
Well, I consider the issue closed... in the end it was not related to a Multiply design problem.
