### ISSUE TITLE
Loading TAP files in real speed issue

### ISSUE THREAD

**Issue by repetto74** [mad3001/Multiply#5]
Hi,

I have the Multiply add-on and it works perfect to browse and load games in SNA, Z80 and TAP format. 
But for an unknown reason I cannot get any TAP to be loaded with settings to load it in real speed. I just get the white prompt and nothing happens.
The ZX spectrum do load normally any TAP file with a TZX Duino but does not work with the Multiply.

**Comment by mad3001** [comment]
Hi @repetto74 .
“Real” loading is an option not implemented in Dandanator 2.x + Multiply (or in all-in-one interfaces that include both). At the moment only “fast” loading can be used for TAP loading.

**Comment by repetto74** [comment]
Ok that explains then :-)! Thank you for your answer.
